name: app_architecture_example
description: "A MiniCore Architecture Example"

publish_to: "none"

version: 0.3.4

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  http: ^1.1.0
  json_annotation: ^4.9.0
  result_dart: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.14
  faker: ^2.2.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.3
  mocktail: ^0.3.0
  test: ^1.25.0
  very_good_analysis: ^6.0.0

dependency_overrides:
  analyzer: ^7.0.0
  test_api: ^0.7.4

flutter:
  uses-material-design: true
